unirecka/main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
]

unirecka/unirecka/urls.py
from django.conf.urls.i18n import i18n_patterns, set_language
from django.contrib import admin
from django.urls import include, path

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("account/", include("account.urls")),
    path("university/", include("universities.urls")),
    path("set_language/", set_language, name="set_language"),
)

unirecka/universities/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

urlpatterns = [
    path("", views.university_list, name="university_list"),
    path("<int:pk>/", views.UniversityDetailView.as_view(), name="university_detail"),
    path("review/<int:pk>/", views.ReviewDetailView.as_view(), name="review_detail"),
    path(
        "review/history/<int:pk>/",
        login_required(views.ReviewHistoryListView.as_view()),
        name="review_history",
    ),
    path(
        "review/create/<int:university_id>/",
        login_required(views.ReviewCreateView.as_view()),
        name="review_create",
    ),
    path(
        "review/delete/<int:pk>/",
        login_required(views.ReviewDeleteView.as_view()),
        name="review_delete",
    ),
    path(
        "review/edit/<int:pk>/",
        login_required(views.ReviewUpdateView.as_view()),
        name="review_update",
    ),
    path(
        "review/report/<int:review_id>/",
        views.ReviewReportCreateView.as_view(),
        name="review_report_create",
    ),
    path("review/like", views.review_like, name="like"),
    path(
        "review/create/comment/<int:review_id>/",
        login_required(views.CommentCreateView.as_view()),
        name="comment_create",
    ),
    path(
        "review/edit/comment/<int:pk>/",
        login_required(views.CommentUpdateView.as_view()),
        name="comment_update",
    ),
    path(
        "review/comment/history/<int:pk>/",
        login_required(views.CommentHistoryListView.as_view()),
        name="comment_history",
    ),
    path(
        "review/delete/comment/<int:pk>/",
        login_required(views.CommentDeleteView.as_view()),
        name="comment_delete",
    ),
    path(
        "review/report/<int:review_id>/comment/<int:comment_id>/",
        views.CommentReportCreateView.as_view(),
        name="comment_report_create",
    ),
]

unirecka/universities/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone


class University(models.Model):
    name = models.CharField(max_length=150)
    search_name = models.CharField(max_length=150, blank=True)
    voivodeship = models.CharField(max_length=150)
    city = models.CharField(max_length=150)
    link = models.CharField(max_length=150)

    class Meta:
        verbose_name = "University"
        verbose_name_plural = "Universities"

    def __str__(self):
        return self.name


class Review(models.Model):
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=3000)
    rating = models.IntegerField(
        validators=[MaxValueValidator(5), MinValueValidator(1)]
    )
    add_date = models.DateTimeField(default=timezone.now, blank=True)
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    users_like = models.ManyToManyField(User, related_name="images_liked", blank=True)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Review"
        verbose_name_plural = "Reviews"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.pk:
            previous_review = Review.objects.get(pk=self.pk)
            if (
                self.title != previous_review.title
                or self.description != previous_review.description
            ):
                ReviewHistory.objects.create(
                    review=previous_review,
                    title=previous_review.title,
                    description=previous_review.description,
                    rating=previous_review.rating,
                    modified_by=self.user,
                )
        super(Review, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        ReviewHistory.objects.create(
            review=self,
            title=self.title,
            description=self.description,
            rating=self.rating,
            modified_by=self.user,
        )
        self.active = False
        self.save()


class ReviewHistory(models.Model):
    review = models.ForeignKey(Review, on_delete=models.SET_NULL, blank=True, null=True)
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=3000)
    rating = models.IntegerField()
    modified_date = models.DateTimeField(default=timezone.now)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"History for Review: {self.review.title} ({self.modified_date})"


class Comment(models.Model):
    description = models.CharField(max_length=3000)
    add_date = models.DateTimeField(default=timezone.now, blank=True)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

    def __str__(self):
        return self.description

    def save(self, *args, **kwargs):
        if self.pk:
            previous_comment = Comment.objects.get(pk=self.pk)
            if self.description != previous_comment.description:
                CommentHistory.objects.create(
                    comment=previous_comment,
                    description=previous_comment.description,
                    modified_by=self.user,
                )
        super(Comment, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        CommentHistory.objects.create(
            comment=self,
            description=self.description,
            modified_by=self.user,
        )
        self.active = False
        self.save()


class CommentHistory(models.Model):
    comment = models.ForeignKey(
        Comment, on_delete=models.SET_NULL, blank=True, null=True
    )
    description = models.CharField(max_length=3000)
    modified_date = models.DateTimeField(default=timezone.now)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"History for Comment: {self.comment.description} ({self.modified_date})"


class ReviewReport(models.Model):
    description = models.CharField(max_length=3000)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "ReviewReport"
        verbose_name_plural = "ReviewReports"

    def __str__(self):
        return self.description


class CommentReport(models.Model):
    description = models.CharField(max_length=3000)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "CommentReport"
        verbose_name_plural = "CommentReports"

    def __str__(self):
        return self.description

unirecka/universities/views.py
from datetime import datetime, time

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Avg, Count, Q
from django.http import Http404, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext as _
from django.views.decorators.http import require_POST
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from unidecode import unidecode

from .models import (
    Comment,
    CommentHistory,
    CommentReport,
    Review,
    ReviewHistory,
    ReviewReport,
    University,
)
from .utils import check_if_has_cursed_words


def university_list(request):
    name = request.GET.get("name", "")
    city = request.GET.get("city", "")
    voivodeship = request.GET.get("voivodeship", "")
    universities = University.objects.all()
    city_and_voivodeship = {}

    for uni in universities:
        city_and_voivodeship[uni.city] = uni.voivodeship

    cities = universities.values_list("city", flat=True).distinct()
    voivodeships = universities.values_list("voivodeship", flat=True).distinct()

    if name != "":
        universities = universities.filter(search_name__icontains=unidecode(name))

    if city != "":
        if voivodeship == "":
            universities = universities.filter(city=city)
        elif voivodeship != city_and_voivodeship[city]:
            messages.warning(
                request,
                _(
                    "Wybrano województwo, w którym nie znajduje się miasto %(city)s. Domyślnie wybrano województwo %(voivodeship)s."
                )
                % {
                    "city": city,
                    "voivodeship": city_and_voivodeship[city].capitalize(),
                },
            )
            universities = universities.filter(
                voivodeship=city_and_voivodeship[city], city=city
            )
            voivodeship = city_and_voivodeship[city]
            universities = universities.annotate(
                avg_rating=Avg("review__rating", filter=Q(review__active=True))
            )

            return render(
                request,
                "universities/university_list.html",
                {
                    "universities": universities,
                    "name_value": name,
                    "city_value": city,
                    "voivodeship_value": voivodeship,
                    "cities": sorted(cities),
                    "voivodeships": sorted(voivodeships),
                },
            )

        universities = universities.filter(
            voivodeship=city_and_voivodeship[city], city=city
        )
        universities = universities.annotate(
            avg_rating=Avg("review__rating", filter=Q(review__active=True))
        )

        return render(
            request,
            "universities/university_list.html",
            {
                "universities": universities,
                "name_value": name,
                "city_value": city,
                "voivodeship_value": voivodeship,
                "cities": sorted(cities),
                "voivodeships": sorted(voivodeships),
            },
        )

    if voivodeship != "":
        if city == "":
            universities = universities.filter(voivodeship=voivodeship)

    universities = universities.annotate(
        avg_rating=Avg("review__rating", filter=Q(review__active=True))
    )

    return render(
        request,
        "universities/university_list.html",
        {
            "universities": universities,
            "name_value": name,
            "city_value": city,
            "voivodeship_value": voivodeship,
            "cities": sorted(cities),
            "voivodeships": sorted(voivodeships),
        },
    )


class UniversityDetailView(DetailView):
    model = University
    template_name = "universities/university_detail.html"
    context_object_name = "university"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        university = self.get_object()

        sort_method = self.request.GET.get("sort_method", "newest")
        start_date = self.request.GET.get("start_date", "")
        end_date = self.request.GET.get("end_date", "")

        allowed_sort_methods = [
            "newest",
            "oldest",
            "most_comments",
            "most_likes",
            "best_ratings",
            "worst_ratings",
        ]
        if sort_method not in allowed_sort_methods:
            raise Http404("Invalid sort method")

        if sort_method == "newest":
            reviews = university.review_set.all().order_by("-add_date")
        elif sort_method == "oldest":
            reviews = university.review_set.all().order_by("add_date")
        elif sort_method == "most_comments":
            reviews = university.review_set.annotate(
                num_comments=Count("comment")
            ).order_by("-num_comments", "-add_date")
        elif sort_method == "most_likes":
            reviews = university.review_set.annotate(
                num_likes=Count("users_like")
            ).order_by("-num_likes", "-add_date")
        elif sort_method == "best_ratings":
            reviews = university.review_set.all().order_by("-rating")
        elif sort_method == "worst_ratings":
            reviews = university.review_set.all().order_by("rating")

        context["has_reviews"] = bool(reviews.filter(active=True))

        if start_date and end_date:
            if datetime.strptime(start_date, "%Y-%m-%d") > datetime.strptime(
                end_date, "%Y-%m-%d"
            ):
                temp = start_date
                start_date = end_date
                end_date = temp
                messages.info(
                    self.request,
                    _(
                        "Pierwsza data jest większa od drugiej, dlatego poprawiono kolejność."
                    ),
                )

        if start_date:
            reviews = reviews.filter(
                add_date__gte=datetime.combine(
                    datetime.strptime(start_date, "%Y-%m-%d").date(), time.min
                )
            )

        if end_date:
            reviews = reviews.filter(
                add_date__lte=datetime.combine(
                    datetime.strptime(end_date, "%Y-%m-%d").date(), time.max
                )
            )

        reviews = reviews.annotate(
            num_active_comments=Count("comment", filter=Q(comment__active=True))
        )

        context["sort_method"] = sort_method
        context["reviews"] = reviews.filter(active=True)

        context["oldest_review_date"] = start_date if start_date else ""
        context["newest_review_date"] = end_date if end_date else ""

        return context


class ReviewCreateView(CreateView):
    model = Review
    template_name = "universities/review_create.html"
    fields = ["title", "description", "rating"]

    def get_success_url(self):
        return reverse_lazy(
            "university_detail", kwargs={"pk": self.kwargs["university_id"]}
        )

    def form_valid(self, form):
        university = get_object_or_404(University, id=self.kwargs["university_id"])
        form.instance.university = university
        form.instance.user = self.request.user

        description = form.cleaned_data.get("description", "")
        title = form.cleaned_data.get("title", "")

        if check_if_has_cursed_words(title.split()):
            messages.error(
                self.request,
                _("Twój tytuł zawiera niedozwolone słowo, spróbuj ponownie."),
            )
            return HttpResponseRedirect(
                reverse_lazy(
                    "review_create",
                    kwargs={"university_id": self.kwargs["university_id"]},
                )
            )

        if check_if_has_cursed_words(description.split()):
            messages.error(
                self.request,
                _("Twój opis zawiera niedozwolone słowo, spróbuj ponownie."),
            )
            return HttpResponseRedirect(
                reverse_lazy(
                    "review_create",
                    kwargs={"university_id": self.kwargs["university_id"]},
                )
            )

        messages.success(self.request, _("Pomyślnie dodano recenzję."))
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(
            self.request,
            _(
                "Wystąpił błąd podczas dodawania opinii. Sprawdź podane dane. Tytuł nie może być zbyt długi."
            ),
        )
        return super().form_invalid(form)


class ReviewUpdateView(UpdateView):
    model = Review
    template_name = "universities/review_update.html"
    fields = ["title", "description", "rating"]

    def form_valid(self, form):
        description = form.cleaned_data.get("description", "")
        title = form.cleaned_data.get("title", "")

        if check_if_has_cursed_words(title.split()):
            messages.error(
                self.request,
                _("Twój tytuł zawiera niedozwolone słowo, spróbuj ponownie."),
            )
            return HttpResponseRedirect(
                reverse_lazy("review_update", kwargs={"pk": self.object.id})
            )

        if check_if_has_cursed_words(description.split()):
            messages.error(
                self.request,
                _("Twój opis zawiera niedozwolone słowo, spróbuj ponownie."),
            )
            return HttpResponseRedirect(
                reverse_lazy("review_update", kwargs={"pk": self.object.id})
            )
        messages.success(self.request, _("Pomyślnie edytowano recenzję."))
        return super().form_valid(form)

    def form_invalid(self, form):

unirecka/universities/templates/universities/comment_create.html
{% extends "base.html" %}
{% load static i18n %}

{% block css %}
    <link rel="stylesheet" href="{% static 'universities/report_review.css' %}">
{% endblock css %}

{% block title %}
    {% trans "Dodaj komentarz" %}
{% endblock title %}

{% block content %}
    <div class="container mt-5">
        {% for message in messages %}
            <div class="row p-0">
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">{{ message }}</div>
            </div>
        {% endfor %}
        <div class="row">
            <h1 class="p-0 mb-2">{% trans "Dodaj komentarz" %}</h1>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="row mt-4">
                <textarea type="text"
                          id="id_description"
                          name="description"
                          class="form-control text-bg-dark text-area"
                          placeholder="{% trans "Opis" %}"
                          required
                          maxlength="3000"></textarea>
            </div>
            <div class="row mt-4 d-flex justify-content-center align-items-center">
                <input class="btn btn-primary" type="submit" value="{% trans "Dodaj komentarz" %}">
            </div>
        </form>
    </div>
{% endblock content %}

unirecka/universities/templates/universities/comment_delete.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    {% trans "Usuń komentarz" %}
{% endblock title %}

{% block css %}
{% endblock css %}

{% block content %}
    <div class="container mt-5">
        <form method="post">
            {% csrf_token %}
            <div class="d-flex justify-content-center">
                <p class="text-center">{% trans "Czy na pewno chcesz usunąć ten komentarz?" %}</p>
            </div>
            <div class="d-flex justify-content-center mt-3">
                <input type="submit"
                       class="btn btn-danger"
                       value="{% trans "Potwierdź usunięcie komentarza" %}">
            </div>
        </form>
    </div>
{% endblock content %}

unirecka/universities/templates/universities/comment_history_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    {% trans "Historia edycji komentarza" %}
{% endblock title %}

{% block css %}
    <link rel="stylesheet" href="{% static 'universities/review_history.css' %}">
{% endblock css %}

{% block content %}
    <div class="container mt-5">
        <h1 class="p-0">{% trans "Historia komentarza" %}: {{ comment.description|truncatechars:30 }}</h1>

        {% if comment_history_list %}
                {% for history in comment_history_list %}
                    <div class="card bg-dark text-light mt-4">
                        <h5 class="card-header border-bottom">{% trans "Data" %}: {{ history.modified_date|date:"d.m.Y H:i" }}</h5>
                        <div class="card-body">
                            <p class="card-text">{% trans "Opis" %}: {{ history.description }}</p>
                        </div>
                    </div>
                {% endfor %}
        {% else %}
            <p class="p-0 mt-4">{% trans "Brak historii dla tego komentarza." %}</p>
        {% endif %}
    </div>
{% endblock content %}

unirecka/universities/templates/universities/comment_update.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    {% trans "Edytuj komentarz" %}
{% endblock title %}

{% block css %}
    <link rel="stylesheet" href="{% static 'universities/review_create.css' %}">
{% endblock css %}

{% block content %}
    <div class="container mt-5">
        {% for message in messages %}
            <div class="row p-0">
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">{{ message }}</div>
            </div>
        {% endfor %}
        <div class="row">
            <h1 class="p-0">{% trans "Edytuj komentarz" %}</h1>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="row mt-2">
                <label for="id_description" class="form-label p-0">{% trans "Opis" %}</label>
                <textarea type="text"
                          id="id_description"
                          name="description"
                          class="form-control text-bg-dark text-area"
                          placeholder="{% trans "Opis" %}"
                          maxlength="3000"
                          required>{{ comment.description }}</textarea>
            </div>
            <div class="row mt-4 d-flex justify-content-center align-items-center">
                <input class="btn btn-primary" type="submit" value="{% trans "Edytuj komentarz" %}">
            </div>
        </form>
    </div>
{% endblock content %}

unirecka/universities/templates/universities/commentreport_create.html
{% extends "base.html" %}
{% load static i18n %}

{% block css %}
    <link rel="stylesheet" href="{% static 'universities/report_review.css' %}">
{% endblock css %}

{% block title %}
    {% trans "Zgłoś komentarz" %}
{% endblock title %}

{% block content %}
    <div class="container mt-5">
        {% for message in messages %}
            <div class="row p-0">
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">{{ message }}</div>
            </div>
        {% endfor %}
        <div class="row">
            <h1 class="p-0 mb-2">{% trans "Opisz zgłoszenie" %}</h1>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="row mt-4">
                <textarea type="text"
                          id="id_description"
                          name="description"
                          class="form-control text-bg-dark text-area"
                          placeholder="{% trans "Opis" %}"
                          maxlength="3000"
                          required></textarea>
            </div>
            <div class="row mt-4 d-flex justify-content-center align-items-center">
                <input class="btn btn-danger" type="submit" value="{% trans "Zgłoś komentarz" %}">
            </div>
        </form>
    </div>
{% endblock content %}

unirecka/universities/templates/universities/review_create.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    {% trans "Dodaj recenzję" %}
{% endblock title %}

{% block css %}
    <link rel="stylesheet" href="{% static "universities/review_create.css" %}">
{% endblock css %}

{% block content %}
    <div class="container mt-5">
        {% for message in messages %}
            <div class="row p-0">
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">{{ message }}</div>
            </div>
        {% endfor %}
        <div class="row">
            <h1 class="p-0">{% trans "Dodaj recenzję" %}</h1>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="row mt-2">
                <label for="id_title" class="form-label p-0">{% trans "Tytuł" %}</label>
                <input type="text"
                       id="id_title"
                       name="title"
                       class="form-control text-bg-dark"
                       placeholder="{% trans 'Tytuł' %}"
                       required
                       maxlength="150" />
            </div>
            <div class="row mt-2">
                <label for="id_description" class="form-label p-0">{% trans "Opis" %}</label>
                <textarea type="text"
                          id="id_description"
                          name="description"
                          class="form-control text-bg-dark text-area"
                          placeholder="{% trans 'Opis' %}"
                          required
                          maxlength="3000"></textarea>
            </div>
            <div class="row mt-2">
                <label for="id_rating" class="form-label p-0">{% trans "Ocena" %}</label>
                <select class="form-select text-bg-dark"
                        aria-label="{% trans 'Wybierz ocenę' %}"
                        name="rating"
                        required>
                    <option selected value="">{% trans 'Wybierz ocenę' %}</option>
                    <option value="1">⭐☆☆☆☆</option>
                    <option value="2">⭐⭐☆☆☆</option>
                    <option value="3">⭐⭐⭐☆☆</option>
                    <option value="4">⭐⭐⭐⭐☆</option>
                    <option value="5">⭐⭐⭐⭐⭐</option>
                </select>
            </div>
            <div class="row mt-4 d-flex justify-content-center align-items-center">
                <input class="btn btn-primary" type="submit" value="{% trans 'Dodaj recenzję' %}">
            </div>
        </form>
    </div>
{% endblock content %}

unirecka/universities/templates/universities/review_delete.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    {% trans "Usuń recenzję" %}
{% endblock title %}

{% block css %}
{% endblock css %}

{% block content %}
    <div class="container mt-5">
        <form method="post">
            {% csrf_token %}
            <div class="d-flex justify-content-center">
                <p class="text-center">{% trans "Czy na pewno chcesz usunąć tę recenzję?" %}</p>
            </div>
            <div class="d-flex justify-content-center mt-3">
                <input type="submit"
                       class="btn btn-danger"
                       value="{% trans 'Potwierdź usunięcie recenzji' %}">
            </div>
        </form>
    </div>
{% endblock content %}

unirecka/universities/templates/universities/review_update.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    {% trans "Edytuj recenzję" %}
{% endblock title %}

{% block css %}
    <link rel="stylesheet" href="{% static "universities/review_create.css" %}">
{% endblock css %}

{% block content %}
    <div class="container mt-5">
        {% for message in messages %}
            <div class="row p-0">
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">{{ message }}</div>
            </div>
        {% endfor %}
        <div class="row">
            <h1 class="p-0">{% trans "Edytuj recenzję" %}</h1>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="row mt-2">
                <label for="id_title" class="form-label p-0">{% trans "Tytuł" %}</label>
                <input type="text"
                       id="id_title"
                       name="title"
                       value="{{ review.title }}"
                       class="form-control text-bg-dark"
                       placeholder="{% trans "Tytuł" %}"
                       required
                       maxlength="150" />
            </div>
            <div class="row mt-2">
                <label for="id_description" class="form-label p-0">{% trans "Opis" %}</label>
                <textarea type="text"
                          id="id_description"
                          name="description"
                          class="form-control text-bg-dark text-area"
                          placeholder="{% trans "Opis" %}"
                          required
                          maxlength="3000">{{ review.description }}</textarea>
            </div>
            <div class="row mt-2">
                <label for="id_rating" class="form-label p-0">{% trans "Ocena" %}</label>
                <select class="form-select text-bg-dark"
                        id="id_rating"
                        aria-label="{% trans "Wybierz ocenę" %}"
                        name="rating"
                        required>
                    <option {% if review.rating == 1 %}selected{% endif %} value="1">⭐☆☆☆☆</option>
                    <option {% if review.rating == 2 %}selected{% endif %} value="2">⭐⭐☆☆☆</option>
                    <option {% if review.rating == 3 %}selected{% endif %} value="3">⭐⭐⭐☆☆</option>
                    <option {% if review.rating == 4 %}selected{% endif %} value="4">⭐⭐⭐⭐☆</option>
                    <option {% if review.rating == 5 %}selected{% endif %} value="5">⭐⭐⭐⭐⭐</option>
                </select>
            </div>
            <div class="row mt-4 d-flex justify-content-center align-items-center">
                <input class="btn btn-primary" type="submit" value="{% trans "Edytuj recenzję" %}">
            </div>
        </form>
    </div>
{% endblock content %}

unirecka/universities/templates/universities/reviewreport_create.html
{% extends "base.html" %}
{% load static i18n %}

{% block css %}
    <link rel="stylesheet" href={% static "universities/report_review.css" %}>
{% endblock css %}

{% block title %}
    {% trans "Zgłoś recenzję" %}
{% endblock title %}

{% block content %}
    <div class="container mt-5">
        {% for message in messages %}
            <div class="row p-0">
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">{{ message }}</div>
            </div>
        {% endfor %}
        <div class="row">
            <h1 class="p-0 mb-2">{% trans "Opisz zgłoszenie" %}</h1>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="row mt-4">
                <textarea type="text"
                          id="id_description"
                          name="description"
                          class="form-control text-bg-dark text-area"
                          placeholder="{% trans 'Opis' %}"
                          maxlength="3000"
                          required> </textarea>
            </div>
            <div class="row mt-4 d-flex justify-content-center align-items-center">
                <input class="btn btn-danger" type="submit" value="{% trans 'Zgłoś recenzję' %}">
            </div>
        </form>
    </div>
{% endblock content %}